/* Automatically generated by genmodtable.sh - do not edit
 *
 * This file defines a table of all supported proto modules.
 */

struct proto_module;

/* Automatically generated by proto - do not edit
 *
 * This file defines a table of all supported  modules.
 */

struct _module;

#ifndef NET_STEG_APP
extern const proto_module p_mod_chop;
extern const proto_module p_mod_null;
#else
extern const proto_module p_mod_nsl;
#endif

extern const proto_module *const supported_protos[] =
{
#ifndef NET_STEG_APP
  &p_mod_chop,
  &p_mod_null,
#else
  &p_mod_nsl,
#endif
  0
};

