/* Automatically generated by genmodtable.sh - do not edit
 *
 * This file defines a table of all supported steg modules.
 */

struct steg_module;

/* Automatically generated by steg - do not edit
 *
 * This file defines a table of all supported  modules.
 */

struct _module;

extern const steg_module s_mod_embed;
extern const steg_module s_mod_http;
extern const steg_module s_mod_nosteg;
extern const steg_module s_mod_nosteg_rr;

#ifndef NET_STEG_APP
extern const steg_module *const supported_stegs[] =
{
  &s_mod_embed,
  &s_mod_http,
  &s_mod_nosteg,
  &s_mod_nosteg_rr,
  0
};
#else
extern const steg_module *const supported_stegs[] =
{
  &s_mod_http,
  0
};
#endif
